# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['gomfather-kb.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'selenium',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'win32com',
        'win32com.client',
        'openpyxl',
        'openpyxl.workbook',
        'plotly',
        'plotly.graph_objects',
        'plotly.subplots',
        'plotly.express',
        'pandas',
        'numpy',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.dates',
        'seaborn',
        'requests',
        'xml.etree.ElementTree',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide2', 'PyQt5'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='gomfather-kb',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
